[package]
name = "aranet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bluer = { version = "0.17.3", features = ["full"] }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
uuid = "1.12.1"
